import type { Locale } from "./types";

const es: Record<string, string> = {
  "app.name": "AmeWork", "app.skip": "Saltar al contenido", "app.assistant": "Tu asistente personal de empleo",
  "nav.aria": "Navegación principal", "nav.profile": "Mi CV", "nav.search": "Buscar empleos", "nav.results": "Resultados", "nav.interests": "Mis intereses", "nav.settings": "Configuración",
  "common.close": "Cerrar", "common.save": "Guardar", "common.cancel": "Cancelar", "common.edit": "Editar",
  "scene.title": "Estudio de carrera", "scene.subtitle": "Una búsqueda clara, personal y verificable", "scene.3d": "Vista 3D", "scene.2d": "Vista 2D accesible", "scene.workers": "{count} búsquedas activas", "scene.noWorkers": "Sin tareas paralelas", "scene.reduced": "Movimiento reducido activo",
  "agent.coordinator.role": "Coordinadora", "agent.coordinator.responsibility": "Comprueba tu CV, coordina la búsqueda y te comunica los resultados.",
  "agent.scout.role": "Buscadora", "agent.scout.responsibility": "Encuentra vacantes recientes y conserva su procedencia.",
  "agent.fit.role": "Analista", "agent.fit.responsibility": "Compara los requisitos con la información confirmada de tu CV.",
  "agent.tailor.role": "Entrenadora de entrevistas", "agent.tailor.responsibility": "Prepara tu guía personalizada sin inventar experiencia.",
  "agent.reviewer.role": "Revisora", "agent.reviewer.responsibility": "Verifica fechas, enlaces, evidencia y calidad.",
  "status.idle": "Esperando", "status.queued": "En cola", "status.working": "Trabajando", "status.waiting_for_workers": "Coordinando", "status.waiting_for_approval": "Esperando tu decisión", "status.completed": "Finalizado", "status.blocked": "Bloqueado", "status.error": "Error",
  "stage.profile": "Prepara tu CV", "stage.search": "Buscando empleos", "stage.verification": "Verificando fechas y enlaces", "stage.analysis": "Comparando con tu CV", "stage.completed": "Búsqueda terminada", "stage.complete": "Búsqueda terminada", "stage.failed": "La búsqueda no pudo terminar",
  "profile.title": "Mi CV", "profile.subtitle": "Súbelo una vez, revisa el resumen extraído y confírmalo antes de buscar.", "profile.confirmed": "CV confirmado", "profile.pending": "Pendiente de revisión", "profile.import": "Subir mi CV", "profile.importHint": "PDF, DOCX o texto. El archivo permanece en tu equipo.", "profile.importing": "Leyendo CV…", "profile.choose": "Elegir archivo", "profile.name": "Perfil", "profile.extractedFacts": "Datos extraídos", "profile.status": "Estado", "profile.ready": "Listo para buscar", "profile.review": "Revisar resumen", "profile.confirm": "Confirmar mi CV", "profile.confirming": "Confirmando…", "profile.replace": "Reemplazar CV",
  "search.title": "¿Qué trabajo buscas?", "search.subtitle": "Escribe un rol y buscaremos sus equivalentes publicados durante los últimos 30 días.", "search.remoteScope": "Remoto desde Costa Rica", "search.last24": "Publicación verificada", "search.roleLabel": "Nombre del puesto", "search.rolePlaceholder": "Ejemplo: QA, Desarrollador, Analista de datos", "search.searching": "Iniciando…", "search.start": "Buscar ahora", "search.aliasHint": "Ampliaremos automáticamente el rol en español e inglés.", "search.profileRequired": "Primero debes subir, revisar y confirmar tu CV.", "search.trustNote": "Sólo aparecerán resultados de hasta 30 días con fecha y enlace HTTPS verificables. Nunca postularemos por ti.", "search.new": "Nueva búsqueda",
  "results.title": "Empleos encontrados", "results.subtitle": "Resultados verificables de hasta 30 días, comparados con tu CV y filtrables sin otra búsqueda.", "results.verified": "vacantes verificadas", "results.expandedAs": "También buscamos:", "results.partialCoverage": "Una fuente no respondió. Los resultados disponibles siguen siendo válidos, pero la cobertura fue parcial.", "results.emptyTitle": "No encontramos vacantes válidas", "results.emptyBody": "No hubo publicaciones verificables de los últimos 30 días para este rol. Prueba un nombre más amplio.", "results.level.high": "Encaje alto", "results.level.medium": "Encaje medio", "results.level.low": "Encaje bajo", "results.requirements": "Lo que solicitan", "results.strengths": "Fortalezas", "results.gaps": "Brechas", "results.noEvidence": "Abre el análisis para revisar evidencia.", "results.noClearGaps": "No se detectaron brechas claras en el resumen.", "results.analysis": "Ver análisis", "results.apply": "Ir a postularse", "results.interested": "Me interesa", "results.preparing": "Preparando guía…",
  "analysis.matches": "Coincidencias respaldadas", "analysis.noMatches": "No encontramos evidencia directa en el CV confirmado.", "analysis.recommendations": "Recomendaciones para tu CV", "analysis.loaded": "Análisis listo", "analysis.resumeUsed": "CV UTILIZADO", "analysis.spanishResume": "Español", "analysis.englishResume": "Inglés", "analysis.confirmedOnly": "Comparación basada únicamente en hechos confirmados.", "analysis.missing": "Requisitos sin evidencia en el CV",
  "interests.title": "Mis intereses", "interests.subtitle": "Vacantes que elegiste y sus guías de preparación.", "interests.saved": "Guardadas", "interests.emptyTitle": "Aún no tienes intereses", "interests.emptyBody": "Pulsa “Me interesa” en una vacante para generar su guía de entrevista.", "interests.savedRole": "Vacante guardada", "interests.download": "Descargar guía PDF", "interests.remove": "Quitar",
  "settings.title": "Configuración y privacidad", "settings.subtitle": "Tú controlas la credencial y los datos que se comparten con DeepSeek.", "settings.cvTitle": "Tu CV", "settings.cv": "El archivo original permanece en este equipo y nunca se envía a portales de empleo.", "settings.applicationsTitle": "Postulaciones", "settings.applications": "La aplicación abre el enlace oficial, pero nunca rellena ni envía una candidatura.",
  "notice.profileImported": "CV importado. Revisa el resumen antes de confirmarlo.", "notice.profileReady": "Tus CV quedaron confirmados y ya puedes buscar.", "notice.searchStarted": "Buscando puestos de {role} publicados durante los últimos 30 días.", "notice.searchComplete": "Búsqueda terminada: {jobs} vacantes verificadas.", "notice.guidePreparing": "Analizando la vacante y preparando tu guía PDF…", "notice.guideReady": "Tu guía de entrevista está lista para descargar.",
  "event.career.search.started": "Iniciando la búsqueda de puestos de {role}…", "event.career.search.scouting": "Buscando estos roles equivalentes: {aliases}.", "event.career.search.found": "Se encontraron {jobs} publicaciones para verificar.", "event.career.search.verifying": "Verificando fechas, ubicación y enlaces de postulación…", "event.career.search.verified": "Se confirmaron {jobs} vacantes de los últimos 30 días.", "event.career.search.comparing": "Comparando {jobs} vacantes con el CV correspondiente…", "event.career.search.compared": "Los {jobs} resúmenes de encaje están listos.", "event.career.search.completed": "Búsqueda terminada: {jobs} vacantes válidas.", "event.career.search.failed": "La búsqueda no pudo terminar. Revisa la conexión y vuelve a intentarlo.", "event.generic": "El sistema registró una actualización.",
  "event.career.guide.started": "Preparando la guía para {role}…", "event.career.guide.analyzing": "Comparando los requisitos con tus conocimientos confirmados…", "event.career.guide.writing": "Construyendo la guía en {language} sin inventar experiencia…", "event.career.guide.rendering": "Generando y verificando el archivo PDF…", "event.career.guide.ready": "Tu guía PDF está lista para descargar.", "event.career.guide.failed": "No se pudo crear el PDF. Puedes volver a intentarlo.",
};

const en: Record<string, string> = {
  ...es,
  "app.skip": "Skip to content", "app.assistant": "Your personal job assistant",
  "nav.aria": "Primary navigation", "nav.profile": "My résumé", "nav.search": "Find jobs", "nav.results": "Results", "nav.interests": "My interests", "nav.settings": "Settings",
  "common.close": "Close", "common.save": "Save", "common.cancel": "Cancel", "common.edit": "Edit",
  "scene.title": "Career studio", "scene.subtitle": "One clear, personal, and verifiable search", "scene.3d": "3D view", "scene.2d": "Accessible 2D view", "scene.workers": "{count} active searches", "scene.noWorkers": "No parallel tasks", "scene.reduced": "Reduced motion active",
  "agent.coordinator.role": "Coordinator", "agent.coordinator.responsibility": "Checks your résumé, coordinates the search, and reports results.", "agent.scout.role": "Scout", "agent.scout.responsibility": "Finds recent roles and preserves their provenance.", "agent.fit.role": "Analyst", "agent.fit.responsibility": "Compares requirements with your confirmed résumé.", "agent.tailor.role": "Interview coach", "agent.tailor.responsibility": "Prepares your guide without inventing experience.", "agent.reviewer.role": "Reviewer", "agent.reviewer.responsibility": "Verifies dates, links, evidence, and quality.",
  "status.idle": "Waiting", "status.queued": "Queued", "status.working": "Working", "status.waiting_for_workers": "Coordinating", "status.waiting_for_approval": "Waiting for you", "status.completed": "Finished", "status.blocked": "Blocked", "status.error": "Error",
  "stage.profile": "Prepare your résumé", "stage.search": "Finding jobs", "stage.verification": "Verifying dates and links", "stage.analysis": "Comparing your résumé", "stage.completed": "Search complete", "stage.complete": "Search complete", "stage.failed": "Search failed",
  "profile.title": "My résumé", "profile.subtitle": "Upload it once, review the extracted summary, and confirm it before searching.", "profile.confirmed": "Résumé confirmed", "profile.pending": "Review required", "profile.import": "Upload my résumé", "profile.importHint": "PDF, DOCX, or text. The file stays on your computer.", "profile.importing": "Reading résumé…", "profile.choose": "Choose file", "profile.name": "Profile", "profile.extractedFacts": "Extracted facts", "profile.status": "Status", "profile.ready": "Ready to search", "profile.review": "Review summary", "profile.confirm": "Confirm my résumé", "profile.confirming": "Confirming…", "profile.replace": "Replace résumé",
  "search.title": "What job are you looking for?", "search.subtitle": "Enter a role and we will search its equivalents posted during the last 30 days.", "search.remoteScope": "Remote from Costa Rica", "search.last24": "Verified publication", "search.roleLabel": "Role name", "search.rolePlaceholder": "Example: QA, Developer, Data analyst", "search.searching": "Starting…", "search.start": "Search now", "search.aliasHint": "We will automatically expand the role in Spanish and English.", "search.profileRequired": "Upload, review, and confirm your résumé first.", "search.trustNote": "Only results up to 30 days old with a verified date and HTTPS link are shown. We never apply for you.", "search.new": "New search",
  "results.title": "Jobs found", "results.subtitle": "Verifiable results up to 30 days old, compared with your résumé and filterable without another search.", "results.verified": "verified roles", "results.expandedAs": "Also searched:", "results.partialCoverage": "One source did not respond. Available results remain valid, but coverage was partial.", "results.emptyTitle": "No valid roles found", "results.emptyBody": "There were no verifiable posts from the last 30 days. Try a broader role name.", "results.level.high": "High fit", "results.level.medium": "Medium fit", "results.level.low": "Low fit", "results.requirements": "What they request", "results.strengths": "Strengths", "results.gaps": "Gaps", "results.noEvidence": "Open the analysis to review evidence.", "results.noClearGaps": "No clear gaps were detected in the summary.", "results.analysis": "View analysis", "results.apply": "Go apply", "results.interested": "I'm interested", "results.preparing": "Preparing guide…",
  "analysis.matches": "Supported matches", "analysis.noMatches": "No direct evidence was found in the confirmed résumé.", "analysis.recommendations": "Résumé recommendations", "analysis.loaded": "Analysis ready", "analysis.resumeUsed": "RÉSUMÉ USED", "analysis.spanishResume": "Spanish", "analysis.englishResume": "English", "analysis.confirmedOnly": "Comparison based only on confirmed facts.", "analysis.missing": "Requirements without résumé evidence",
  "interests.title": "My interests", "interests.subtitle": "Roles you selected and their preparation guides.", "interests.saved": "Saved", "interests.emptyTitle": "No interests yet", "interests.emptyBody": "Press “I'm interested” on a role to create its interview guide.", "interests.savedRole": "Saved role", "interests.download": "Download PDF guide", "interests.remove": "Remove",
  "settings.title": "Settings and privacy", "settings.subtitle": "You control the credential and the information shared with DeepSeek.", "settings.cvTitle": "Your résumé", "settings.cv": "The original file remains on this computer and is never sent to job boards.", "settings.applicationsTitle": "Applications", "settings.applications": "The app opens the official link but never completes or submits an application.",
  "notice.profileImported": "Résumé imported. Review the summary before confirming it.", "notice.profileReady": "Both résumés are confirmed and ready for searching.", "notice.searchStarted": "Searching for {role} positions posted during the last 30 days.", "notice.searchComplete": "Search complete: {jobs} verified roles.", "notice.guidePreparing": "Analyzing the job and preparing your PDF guide…", "notice.guideReady": "Your interview guide is ready to download.",
  "event.career.search.started": "Starting the search for {role} roles…", "event.career.search.scouting": "Searching these equivalent roles: {aliases}.", "event.career.search.found": "Found {jobs} postings to verify.", "event.career.search.verifying": "Verifying dates, location, and application links…", "event.career.search.verified": "Confirmed {jobs} roles from the last 30 days.", "event.career.search.comparing": "Comparing {jobs} roles with the matching résumé…", "event.career.search.compared": "All {jobs} fit summaries are ready.", "event.career.search.completed": "Search complete: {jobs} valid roles.", "event.career.search.failed": "The search failed. Check the connection and try again.", "event.generic": "The system recorded an update.",
  "event.career.guide.started": "Preparing the guide for {role}…", "event.career.guide.analyzing": "Comparing requirements with your confirmed knowledge…", "event.career.guide.writing": "Building the guide in {language} without inventing experience…", "event.career.guide.rendering": "Generating and validating the PDF file…", "event.career.guide.ready": "Your PDF guide is ready to download.", "event.career.guide.failed": "The PDF could not be created. You can try again.",
};

const copy: Record<Locale, Record<string, string>> = { es, en };
export type Translate = (key: string, variables?: Record<string, string | number | boolean>) => string;
export function createTranslator(locale: Locale): Translate {
  return (key, variables = {}) => (copy[locale][key] ?? es[key] ?? key).replace(/\{(\w+)\}/g, (_, name: string) => String(variables[name] ?? `{${name}}`));
}
